/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/Register': RouteRecordInfo<'/auth/Register', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/products/Create': RouteRecordInfo<'/products/Create', '/products/Create', Record<never, never>, Record<never, never>>,
    '/products/ShowAll': RouteRecordInfo<'/products/ShowAll', '/products/ShowAll', Record<never, never>, Record<never, never>>,
    '/products/update/[id]': RouteRecordInfo<'/products/update/[id]', '/products/update/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/Login.vue': {
      routes: '/auth/Login'
      views: never
    }
    'src/pages/auth/Register.vue': {
      routes: '/auth/Register'
      views: never
    }
    'src/pages/products/Create.vue': {
      routes: '/products/Create'
      views: never
    }
    'src/pages/products/ShowAll.vue': {
      routes: '/products/ShowAll'
      views: never
    }
    'src/pages/products/update/[id].vue': {
      routes: '/products/update/[id]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
